/**
 * Permission Map
 * Mapeia nomes de permissões para IDs do ts_interface
 *
 * IMPORTANTE: Estes IDs devem corresponder aos pk da tabela ts_interface
 * Para facilitar manutenção, use nomes descritivos em vez de IDs hardcoded
 */

/**
 * IDs de Permissões (ts_interface.pk)
 * Baseado na estrutura do backend
 */
export const PERMISSIONS = {
  // ==================== ADMIN (10-99) ====================
  ADMIN_DASHBOARD: 10,
  ADMIN_USERS: 20,
  ADMIN_PAYMENTS: 30,
  SYSTEM_CONFIG: 40,
  SYSTEM_LOGS: 50,
  ADMIN_CACHE_MANAGE: 110,

  // ==================== TASKS (200-299) ====================
  TASKS_VIEW: 200,
  TASKS_MY: 201, // Ver apenas minhas tarefas
  TASKS_CREATE: 210,
  TASKS_EDIT: 220,
  TASKS_DELETE: 230,
  TASKS_ASSIGN: 240,
  TASKS_COMPLETE: 250,
  TASKS_CONTROL: 260, // Controlo de tarefas (gestores)

  // ==================== OPERATIONS (300-399) ====================
  OPERATIONS_VIEW: 300,
  OPERATIONS_CREATE: 310,
  OPERATIONS_ETAR: 320,
  OPERATIONS_EE: 330,
  OPERATIONS_NETWORK: 340,
  OPERATIONS_BOXES: 350,
  OPERATIONS_EDIT: 360,
  OPERATIONS_DELETE: 370,

  // ==================== BRANCHES - RAMAIS (400-449) ====================
  BRANCHES_VIEW: 400,
  BRANCHES_CREATE: 410,
  BRANCHES_EDIT: 420,
  BRANCHES_DELETE: 430,

  // ==================== SEPTIC TANKS - FOSSAS (450-499) ====================
  SEPTIC_TANKS_VIEW: 450,
  SEPTIC_TANKS_MANAGE: 460,
  SEPTIC_TANKS_EDIT: 470,
  SEPTIC_TANKS_DELETE: 480,

  // ==================== DOCUMENTS (500-599) ====================
  DOCS_VIEW_ALL: 500,
  DOCS_VIEW_OWNER: 510,
  DOCS_VIEW_ASSIGNED: 520,
  DOCS_CREATE: 530,
  DOCS_EDIT: 540,
  DOCS_DELETE: 550,
  DOCS_ASSIGN: 560,
  DOCS_APPROVE: 570,

  // ==================== ETAR (600-649) ====================
  ETAR_VIEW: 600,
  ETAR_VIEW_CHARACTERISTICS: 610,
  ETAR_VIEW_VOLUMES: 620,
  ETAR_VIEW_ENERGY: 630,
  ETAR_VIEW_EXPENSES: 640,
  ETAR_VIEW_VIOLATIONS: 645,
  ETAR_EDIT: 650,

  // ==================== ESTAÇÕES ELEVATÓRIAS - EE (650-699) ====================
  EE_VIEW: 660,
  EE_VIEW_CHARACTERISTICS: 665,
  EE_VIEW_VOLUMES: 670,
  EE_VIEW_ENERGY: 675,
  EE_VIEW_EXPENSES: 680,
  EE_EDIT: 690,

  // ==================== ANÁLISES (700-749) ====================
  ANALYSES_VIEW: 700,
  ANALYSES_CREATE: 710,
  ANALYSES_EDIT: 720,
  ANALYSES_DELETE: 730,

  // ==================== TELEMETRIA (750-799) ====================
  TELEMETRY_VIEW: 750,
  TELEMETRY_CONFIG: 760,
  TELEMETRY_EDIT: 770,

  // ==================== ENTITIES (800-849) ====================
  ENTITIES_VIEW: 800,
  ENTITIES_EDIT: 810,
  ENTITIES_CREATE: 820,
  ENTITIES_DELETE: 830,

  // ==================== PAGAMENTOS (850-899) ====================
  PAYMENTS_VIEW: 850,
  PAYMENTS_VALIDATE: 860,
  PAYMENTS_REFUND: 870,
  PAYMENTS_PROCESS: 880,
  PAYMENTS_APPROVE: 890,

  // ==================== INVOICES - FATURAS (900-949) ====================
  INVOICES_VIEW: 900,
  INVOICES_CREATE: 910,
  INVOICES_EDIT: 920,
  INVOICES_CANCEL: 930,

  // ==================== CLIENTS - CLIENTES (950-999) ====================
  CLIENTS_VIEW: 950,
  CLIENTS_CREATE: 960,
  CLIENTS_EDIT: 970,
  CLIENTS_CONTRACTS: 980,
  CLIENTS_DELETE: 990,

  // ==================== DASHBOARDS (1000-1099) ====================
  DASHBOARD_VIEW: 1000,
  DASHBOARD_TASKS: 1010,
  DASHBOARD_BRANCHES: 1020,
  DASHBOARD_SEPTIC_TANKS: 1030,
  DASHBOARD_INSTALLATIONS: 1040,
  DASHBOARD_VIOLATIONS: 1050,
  DASHBOARD_ANALYSES: 1060,

  // ==================== EPI (1100-1149) ====================
  EPI_MANAGEMENT: 1100,
  EPI_ASSIGN: 1110,
  EPI_TRACK: 1120,
  EPI_VIEW: 1130,

  // ==================== INVENTÁRIO (1150-1199) ====================
  INVENTORY_VIEW: 1150,
  INVENTORY_MOVEMENTS: 1160,
  INVENTORY_ADJUST: 1170,
  INVENTORY_CREATE: 1180,

  // ==================== PAVIMENTAÇÕES (1200-1249) ====================
  PAVEMENTS_VIEW: 1200,
  PAVEMENTS_MANAGE: 1210,
  PAVEMENTS_EDIT: 1220,

  // ==================== DESPESAS (1250-1299) ====================
  EXPENSES_VIEW: 1250,
  EXPENSES_CREATE: 1260,
  EXPENSES_APPROVE: 1270,
  EXPENSES_EDIT: 1280,

  // ==================== OFÍCIOS (1300-1349) ====================
  OFFICES_VIEW: 1300,
  OFFICES_CREATE: 1310,
  OFFICES_EDIT: 1320,
  OFFICES_CLOSE: 1330,
  OFFICES_REPLICATE: 1340,

  // ==================== REQUESTS - PEDIDOS GESTÃO (1350-1399) ====================
  REQUESTS_VIEW: 1350,
  REQUESTS_CREATE: 1360,
  REQUESTS_EDIT: 1370,
  REQUESTS_CLOSE: 1380,
  REQUESTS_REPLICATE: 1390,

  // ==================== SIBS (1400-1449) ====================
  SIBS_VIEW: 1400,
  SIBS_PROCESS: 1410,
};

/**
 * Obter nome da permissão pelo ID
 * @param {number} permissionId
 * @returns {string|null}
 */
export const getPermissionName = (permissionId) => {
  const entry = Object.entries(PERMISSIONS).find(([_, id]) => id === permissionId);
  return entry ? entry[0] : null;
};

/**
 * Obter ID da permissão pelo nome
 * @param {string} permissionName
 * @returns {number|null}
 */
export const getPermissionId = (permissionName) => {
  return PERMISSIONS[permissionName] || null;
};

/**
 * Perfis de utilizador pré-configurados
 */
export const USER_PROFILES = {
  SUPER_ADMIN: '0',
  OPERADOR: '1',
  TECNICO: '2',
  FINANCEIRO: '3',
  GESTOR: '4',
  ADMIN: '5',
};

/**
 * Grupos de Permissões
 * Útil para atribuir múltiplas permissões de uma vez
 * Mapeamento de perfis para permissões (referência - backend controla as permissões reais)
 */
export const PERMISSION_GROUPS = {
  // Super Admin - Acesso total
  SUPER_ADMIN: Object.values(PERMISSIONS),

  // Operador - Apenas módulo Operação
  OPERADOR: [
    PERMISSIONS.TASKS_MY,
    PERMISSIONS.TASKS_VIEW,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.OPERATIONS_VIEW,
    PERMISSIONS.OPERATIONS_CREATE,
    PERMISSIONS.BRANCHES_VIEW,
    PERMISSIONS.SEPTIC_TANKS_VIEW,
  ],

  // Técnico - Operação + Gestão
  TECNICO: [
    PERMISSIONS.TASKS_VIEW,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_EDIT,
    PERMISSIONS.TASKS_ASSIGN,
    PERMISSIONS.OPERATIONS_VIEW,
    PERMISSIONS.OPERATIONS_CREATE,
    PERMISSIONS.OPERATIONS_ETAR,
    PERMISSIONS.OPERATIONS_EE,
    PERMISSIONS.OPERATIONS_NETWORK,
    PERMISSIONS.OPERATIONS_BOXES,
    PERMISSIONS.ETAR_VIEW,
    PERMISSIONS.ETAR_VIEW_CHARACTERISTICS,
    PERMISSIONS.ETAR_VIEW_VOLUMES,
    PERMISSIONS.ETAR_VIEW_ENERGY,
    PERMISSIONS.EE_VIEW,
    PERMISSIONS.EE_VIEW_CHARACTERISTICS,
    PERMISSIONS.EE_VIEW_VOLUMES,
    PERMISSIONS.ANALYSES_VIEW,
    PERMISSIONS.ANALYSES_CREATE,
    PERMISSIONS.TELEMETRY_VIEW,
    PERMISSIONS.BRANCHES_VIEW,
    PERMISSIONS.BRANCHES_CREATE,
    PERMISSIONS.SEPTIC_TANKS_VIEW,
    PERMISSIONS.SEPTIC_TANKS_MANAGE,
  ],

  // Financeiro - Pagamentos + Dashboards
  FINANCEIRO: [
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_VALIDATE,
    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.INVOICES_CREATE,
    PERMISSIONS.INVOICES_EDIT,
    PERMISSIONS.CLIENTS_VIEW,
    PERMISSIONS.CLIENTS_CREATE,
    PERMISSIONS.CLIENTS_EDIT,
    PERMISSIONS.CLIENTS_CONTRACTS,
    PERMISSIONS.SIBS_VIEW,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_TASKS,
  ],

  // Gestor - Tudo exceto Administração
  GESTOR: [
    // Operação
    PERMISSIONS.TASKS_VIEW,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_EDIT,
    PERMISSIONS.TASKS_ASSIGN,
    PERMISSIONS.TASKS_CONTROL,
    PERMISSIONS.OPERATIONS_VIEW,
    PERMISSIONS.OPERATIONS_CREATE,
    PERMISSIONS.BRANCHES_VIEW,
    PERMISSIONS.BRANCHES_CREATE,
    PERMISSIONS.SEPTIC_TANKS_VIEW,
    PERMISSIONS.SEPTIC_TANKS_MANAGE,
    // Gestão
    PERMISSIONS.ETAR_VIEW,
    PERMISSIONS.ETAR_VIEW_CHARACTERISTICS,
    PERMISSIONS.ETAR_VIEW_VOLUMES,
    PERMISSIONS.ETAR_VIEW_ENERGY,
    PERMISSIONS.ETAR_VIEW_EXPENSES,
    PERMISSIONS.ETAR_VIEW_VIOLATIONS,
    PERMISSIONS.EE_VIEW,
    PERMISSIONS.EE_VIEW_CHARACTERISTICS,
    PERMISSIONS.EE_VIEW_VOLUMES,
    PERMISSIONS.EE_VIEW_ENERGY,
    PERMISSIONS.EE_VIEW_EXPENSES,
    PERMISSIONS.ANALYSES_VIEW,
    PERMISSIONS.ANALYSES_CREATE,
    PERMISSIONS.TELEMETRY_VIEW,
    PERMISSIONS.EXPENSES_VIEW,
    PERMISSIONS.EXPENSES_CREATE,
    PERMISSIONS.PAVEMENTS_VIEW,
    // Pagamentos
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.CLIENTS_VIEW,
    // Dashboards
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_TASKS,
    PERMISSIONS.DASHBOARD_BRANCHES,
    PERMISSIONS.DASHBOARD_INSTALLATIONS,
    PERMISSIONS.DASHBOARD_ANALYSES,
    // Administrativo
    PERMISSIONS.EPI_MANAGEMENT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.OFFICES_VIEW,
  ],

  // Admin - Acesso completo
  ADMIN: Object.values(PERMISSIONS),

  // Legacy groups (manter compatibilidade)
  TASK_MANAGER: [
    PERMISSIONS.TASKS_VIEW,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_EDIT,
    PERMISSIONS.TASKS_DELETE,
    PERMISSIONS.TASKS_ASSIGN,
  ],

  DOCUMENT_MANAGER: [
    PERMISSIONS.DOCS_VIEW_ALL,
    PERMISSIONS.DOCS_CREATE,
    PERMISSIONS.DOCS_EDIT,
    PERMISSIONS.DOCS_DELETE,
    PERMISSIONS.DOCS_ASSIGN,
    PERMISSIONS.DOCS_APPROVE,
  ],

  BASIC_USER: [
    PERMISSIONS.TASKS_MY,
    PERMISSIONS.DOCS_VIEW_OWNER,
    PERMISSIONS.DOCS_VIEW_ASSIGNED,
  ],
};

export default PERMISSIONS;
