// services/documentToEmissionMapper.js
// Mapeamento inteligente entre dados de documentos e variáveis de templates
import { getEntityByNIF } from './entityService';

/**
 * Mapeia dados de um documento para as variáveis de um template de emissão
 * IMPORTANTE: Busca dados da ENTIDADE via NIF para preencher header (destinatário oficial)
 *             e usa dados do DOCUMENTO para body (dados específicos da intervenção)
 *
 * @param {Object} document - Dados do documento/pedido (deve conter nipc)
 * @param {Object} template - Template selecionado com metadados
 * @returns {Promise<Object>} - { recipient_data, custom_data } preenchidos
 */
export const mapDocumentToEmissionVariables = async (document, template) => {
  if (!document || !template) {
    console.warn('[DocumentMapper] Documento ou template ausente');
    return { recipient_data: {}, custom_data: {} };
  }

  // 🔍 BUSCAR DADOS DA ENTIDADE VIA NIF
  let entityData = null;
  if (document.nipc) {
    try {
      const response = await getEntityByNIF(document.nipc);
      if (response && response.entity) {
        entityData = response.entity;
        console.log('[DocumentMapper] Dados da entidade obtidos:', entityData.name);
      }
    } catch (error) {
      console.error('[DocumentMapper] Erro ao buscar entidade:', error);
    }
  }

  const recipient_data = {};
  const custom_data = {};

  // Campos auto-gerados (não precisam de mapeamento)
  const autoGeneratedFields = [
    'NUMERO_OFICIO',
    'EMISSION_NUMBER',
    'DATA',
    'DATE',
    'DATA_EMISSAO',
    'ASSUNTO',
    'SUBJECT',
    'CODIGO_TEMPLATE'
  ];

  // ========================================
  // MAPEAMENTO SEPARADO POR SEÇÃO
  // ========================================

  // 📋 HEADER: Dados da ENTIDADE (destinatário oficial)
  const headerFieldMappings = {
    // ⭐ Destinatário = ENTIDADE (dados oficiais cadastrados)
    'DESTINATARIO_NOME': entityData?.name || document.ts_entity || '',
    'NOME_DESTINATARIO': entityData?.name || document.ts_entity || '',
    'NOME': entityData?.name || document.ts_entity || '',

    'DESTINATARIO_MORADA': buildFullAddress(
      entityData?.address || document.address,
      entityData?.floor || document.floor,
      entityData?.door || document.door
    ),
    'MORADA_DESTINATARIO': buildFullAddress(
      entityData?.address || document.address,
      entityData?.floor || document.floor,
      entityData?.door || document.door
    ),
    'MORADA': buildFullAddress(
      entityData?.address || document.address,
      entityData?.floor || document.floor,
      entityData?.door || document.door
    ),  // ⭐ HEADER usa ENTIDADE com address + floor + door

    'DESTINATARIO_CODIGO_POSTAL': entityData?.postal || document.postal || '',
    'CODIGO_POSTAL_DESTINATARIO': entityData?.postal || document.postal || '',
    'CODIGO_POSTAL': entityData?.postal || document.postal || '',  // ⭐ HEADER usa ENTIDADE

    'DESTINATARIO_LOCALIDADE': entityData?.nut4 || document.nut4 || '',
    'LOCALIDADE_DESTINATARIO': entityData?.nut4 || document.nut4 || '',
    'LOCALIDADE': entityData?.nut4 || document.nut4 || '',  // ⭐ HEADER usa ENTIDADE

    'DESTINATARIO_EMAIL': entityData?.email || document.email || '',
    'EMAIL_DESTINATARIO': entityData?.email || document.email || '',
    'EMAIL': entityData?.email || document.email || '',

    // === REFERÊNCIAS DO PEDIDO (automático) ===
    'NUMERO_PEDIDO': document.regnumber || '',
    'DATA_PEDIDO': document.submission ? formatDate(document.submission) : ''

    // ⚠️ SUA_REFERENCIA, SUA_COMUNICACAO (referências DO DESTINATÁRIO)
    // → NÃO mapeados automaticamente - devem ser preenchidos manualmente!
  };

  // 📋 BODY: Dados do DOCUMENTO (intervenção específica)
  const bodyFieldMappings = {
    // ⭐ REQUERENTE = ENTIDADE (pessoa que faz o pedido)
    // ts_associate é o município/associado, NÃO o requerente!
    'NOME_REQUERENTE': entityData?.name || document.ts_entity || '',

    // NIF do requerente = NIF do documento
    'NIF': document.nipc ? String(document.nipc) : (document.nif || document.entity_nipc || ''),

    // Email pode aparecer no BODY também
    'EMAIL': entityData?.email || document.email || '',

    // Morada de intervenção = address + floor + door
    'MORADA_INTERVENCAO': buildFullAddress(
      document.address || document.morada_intervencao,
      document.floor,
      document.door
    ),
    'MORADA': buildFullAddress(
      document.address || document.morada,
      document.floor,
      document.door
    ),

    // Código postal de intervenção = mesmo que postal
    'CODIGO_POSTAL_INTERVENCAO': document.postal || document.codigo_postal_intervencao || '',
    'CODIGO_POSTAL': document.postal || document.codigo_postal || '',

    // Localidade de intervenção = mesma que nut4
    'LOCALIDADE_INTERVENCAO': document.nut4 || document.localidade_intervencao || '',
    'LOCALIDADE': document.nut4 || document.localidade || '',

    // Prioridade: nut3 (campo real) → fallback
    'FREGUESIA': document.nut3 || document.freguesia || '',

    // === REFERÊNCIAS DO PEDIDO (automático) ===
    'NUMERO_PEDIDO': document.regnumber || '',
    'DATA_PEDIDO': document.submission ? formatDate(document.submission) : '',

    // === OUTROS CAMPOS ===
    // Prioridade: door (campo real) → fallback
    'PORTA': document.door || document.porta || '',
    'ANDAR': document.floor || ''

    // ⚠️ SUA_REFERENCIA, SUA_COMUNICACAO (referências DO DESTINATÁRIO)
    // → NÃO mapeados automaticamente - devem ser preenchidos manualmente!
  };

  // ========================================
  // PROCESSAR VARIÁVEIS POR SEÇÃO
  // ========================================

  // ========================================
  // MAPEAMENTO DE NOMES DE CAMPOS
  // ========================================
  // Deve corresponder ao fieldMapping do EmissionForm.jsx para garantir consistência
  const fieldNameMapping = {
    // Destinatário (header)
    'DESTINATARIO_NOME': 'destinatario_nome',
    'NOME_DESTINATARIO': 'destinatario_nome',
    'NOME': 'destinatario_nome',
    'DESTINATARIO_MORADA': 'destinatario_morada',
    'MORADA_DESTINATARIO': 'destinatario_morada',
    'DESTINATARIO_CODIGO_POSTAL': 'destinatario_codigo_postal',
    'CODIGO_POSTAL_DESTINATARIO': 'destinatario_codigo_postal',
    'DESTINATARIO_LOCALIDADE': 'destinatario_localidade',
    'LOCALIDADE_DESTINATARIO': 'destinatario_localidade',
    'DESTINATARIO_EMAIL': 'destinatario_email',
    'EMAIL_DESTINATARIO': 'destinatario_email',
    'EMAIL': 'destinatario_email',  // ⭐ CRÍTICO: EMAIL no header = destinatario_email

    // Requerente/Intervenção (body → recipient_data)
    'NOME_REQUERENTE': 'nome_requerente',
    'NIF': 'nif',
    'MORADA': 'morada',
    'CODIGO_POSTAL': 'codigo_postal',
    'LOCALIDADE': 'localidade',
    'FREGUESIA': 'freguesia',
    'PORTA': 'porta',
    'MORADA_INTERVENCAO': 'morada_intervencao',
    'CODIGO_POSTAL_INTERVENCAO': 'codigo_postal_intervencao',
    'LOCALIDADE_INTERVENCAO': 'localidade_intervencao',

    // Assinatura
    'NOME_ASSINANTE': 'nome_assinante',
    'SIGNATURE_NAME': 'nome_assinante',
    'ASSINATURA_CARGO': 'assinatura_cargo',

    // Referências (custom_data)
    'SUA_REFERENCIA': 'sua_referencia',
    'NUMERO_PEDIDO': 'numero_pedido',
    'SUA_COMUNICACAO': 'sua_comunicacao',
    'DATA_PEDIDO': 'data_pedido',
    'DATA_COMUNICACAO': 'data_comunicacao',
    'DATA_COMUNICACAO_RECEBIDA': 'data_comunicacao_recebida',
    'NOSSA_REFERENCIA': 'nossa_referencia',
    'REFERENCIA_INTERNA': 'referencia_interna',
    'REFERENCIA_DESTINATARIO': 'referencia_destinatario',

    // Template
    'CODIGO_TEMPLATE': 'codigo_template'
  };

  // 1️⃣ HEADER: Usar dados da ENTIDADE
  if (template.meta_data?.variaveis?.header) {
    template.meta_data.variaveis.header.forEach((variable) => {
      const varNameUpper = variable.nome.toUpperCase();

      if (autoGeneratedFields.includes(varNameUpper)) return;

      const fieldName = fieldNameMapping[varNameUpper] || variable.nome.toLowerCase();
      const mappedValue = headerFieldMappings[varNameUpper];

      if (mappedValue !== undefined) {
        custom_data[fieldName] = mappedValue;
      }
    });
  }

  // 2️⃣ BODY: Usar dados do DOCUMENTO
  if (template.meta_data?.variaveis?.body) {
    template.meta_data.variaveis.body.forEach((variable) => {
      const varNameUpper = variable.nome.toUpperCase();

      if (autoGeneratedFields.includes(varNameUpper)) return;

      /**
       * Determinar seção: campos de requerente/intervenção vão para recipient_data
       *
       * IMPORTANTE:
       * - MORADA/CODIGO_POSTAL/LOCALIDADE/FREGUESIA do BODY = dados da INTERVENÇÃO
       * - Vão para recipient_data (não custom_data)
       * - MORADA/CODIGO_POSTAL/LOCALIDADE do HEADER = dados do DESTINATÁRIO
       * - Vão para custom_data (com prefixo destinatario_)
       */
      const isRecipientField = varNameUpper.includes('REQUERENTE') ||
                               varNameUpper.includes('NIF') ||
                               varNameUpper.includes('INTERVENCAO') ||
                               varNameUpper === 'MORADA' ||
                               varNameUpper === 'CODIGO_POSTAL' ||
                               varNameUpper === 'LOCALIDADE' ||
                               varNameUpper === 'FREGUESIA' ||
                               varNameUpper === 'PORTA' ||
                               varNameUpper === 'ANDAR';

      const targetSection = isRecipientField ? recipient_data : custom_data;
      const fieldName = fieldNameMapping[varNameUpper] || variable.nome.toLowerCase();
      const mappedValue = bodyFieldMappings[varNameUpper];

      if (mappedValue !== undefined) {
        targetSection[fieldName] = mappedValue;
      }
    });
  }

  // 3️⃣ FOOTER: Usar dados do DOCUMENTO
  if (template.meta_data?.variaveis?.footer) {
    template.meta_data.variaveis.footer.forEach((variable) => {
      const varNameUpper = variable.nome.toUpperCase();

      if (autoGeneratedFields.includes(varNameUpper)) return;

      const fieldName = fieldNameMapping[varNameUpper] || variable.nome.toLowerCase();
      const mappedValue = bodyFieldMappings[varNameUpper];

      if (mappedValue !== undefined) {
        custom_data[fieldName] = mappedValue;
      }
    });
  }

  // Adicionar referência ao documento original
  custom_data.source_document_pk = document.pk || null;
  custom_data.source_regnumber = document.regnumber || null;
  custom_data.notes = document.obs || document.memo || '';

  return {
    recipient_data,
    custom_data
  };
};

/**
 * Constrói morada completa combinando address, floor e door
 * @param {string} address - Endereço base (rua)
 * @param {string} floor - Andar
 * @param {string} door - Porta
 * @returns {string} Morada completa formatada
 */
const buildFullAddress = (address, floor, door) => {
  if (!address) return '';

  const parts = [address];

  if (floor) {
    parts.push(floor);
  }

  if (door) {
    parts.push(door);
  }

  return parts.join(', ');
};

/**
 * Formata data para formato português
 */
const formatDate = (dateString) => {
  if (!dateString) return '';

  try {
    const date = new Date(dateString);
    if (isNaN(date.getTime())) return dateString;

    const day = String(date.getDate()).padStart(2, '0');
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const year = date.getFullYear();

    return `${day}-${month}-${year}`;
  } catch (error) {
    console.error('[DocumentMapper] Erro ao formatar data:', error);
    return dateString;
  }
};

/**
 * Gera assunto sugerido com base no documento
 */
export const generateSubjectFromDocument = (document) => {
  if (!document) return '';

  const parts = [];

  // Adicionar tipo de documento (tt_type é o campo real)
  if (document.tt_type) {
    parts.push(document.tt_type);
  }

  // Adicionar número de registo
  if (document.regnumber) {
    parts.push(`- Processo nº ${document.regnumber}`);
  }

  // ⭐ NÃO incluir associado/entidade (redundante - já aparece nos dados do destinatário)

  return parts.join(' ') || 'Assunto da emissão';
};

export default {
  mapDocumentToEmissionVariables,
  generateSubjectFromDocument
};
