export default {
  key: 'rh_colaborador', label: 'Colaborador', labelPlural: 'Colaboradores', icon: 'UserCircle',
  db: { readView: 'vbl_rh_colaborador', writeView: 'vbl_rh_colaborador', pkField: 'pk' },
  permissions: { view: 'operation.access', edit: 'operation.manage' },
  fields: [
    { key: 'pk',                      label: 'ID',               type: 'id' },
    { key: 'name',                    label: 'Nome',              type: 'text',    required: true },
    { key: 'email',                   label: 'Email',             type: 'text' },
    { key: 'categoria',               label: 'Categoria',         type: 'text' },
    { key: 'tipo_contrato',           label: 'Tipo Contrato',     type: 'text' },
    { key: 'num_mecanografico',       label: 'Nº Mecanográfico',  type: 'text' },
    { key: 'departamento',            label: 'Departamento',      type: 'text' },
    { key: 'data_admissao',           label: 'Data Admissão',     type: 'date' },
    { key: 'data_nascimento',         label: 'Data Nascimento',   type: 'date' },
    { key: 'superior_nome',           label: 'Superior',          type: 'text',    readonly: true },
    { key: 'elegivel_piquete',        label: 'Elegível Piquete',  type: 'boolean' },
    { key: 'dias_ferias_disponiveis', label: 'Férias Disp.',      type: 'number',  readonly: true },
    { key: 'anos_antiguidade',        label: 'Antiguidade (anos)',type: 'number',  readonly: true },
    { key: 'notas_rh',                label: 'Notas RH',          type: 'textarea' },
  ],
  listView: { columns: ['name', 'categoria', 'departamento', 'tipo_contrato', 'data_admissao'], defaultSort: { field: 'name', dir: 'asc' }, searchable: true },
  formView: { sections: [
    { title: 'Identificação', fields: ['name', 'email', 'num_mecanografico'], cols: 3 },
    { title: 'Contrato',      fields: ['categoria', 'tipo_contrato', 'departamento', 'superior_nome', 'data_admissao'], cols: 2 },
    { title: 'Pessoal',       fields: ['data_nascimento', 'elegivel_piquete'], cols: 2 },
    { title: 'Notas',         fields: ['notas_rh'], cols: 1 },
  ]},
  relations: {
    faltas:   { type: 'hasMany', entity: 'rh_faltas',  foreignKey: 'tb_user_fk', label: 'Faltas',  icon: 'CalendarX' },
    ferias:   { type: 'hasMany', entity: 'rh_ferias',  foreignKey: 'tb_user_fk', label: 'Férias',  icon: 'Umbrella' },
    piquetes: { type: 'hasMany', entity: 'rh_piquete', foreignKey: 'tb_user_fk', label: 'Piquete', icon: 'ShieldAlert' },
    ponto:    { type: 'hasMany', entity: 'rh_ponto',   foreignKey: 'tb_user_fk', label: 'Ponto',   icon: 'Clock' },
  },
  detailView: { tabs: [
    { label: 'Faltas',  relation: 'faltas',   icon: 'CalendarX' },
    { label: 'Férias',  relation: 'ferias',   icon: 'Umbrella' },
    { label: 'Piquete', relation: 'piquetes', icon: 'ShieldAlert' },
    { label: 'Ponto',   relation: 'ponto',    icon: 'Clock' },
  ]},
  custom: null,
}
