export default {
  key: 'site_procedimento', label: 'Procedimento (Site)', labelPlural: 'Procedimentos (Site)', icon: 'ScrollText',
  db: { readView: 'vbl_site_procedimento', writeView: 'vbf_site_procedimento', pkField: 'pk' },
  permissions: { view: 'operation.access', edit: 'operation.manage' },
  fields: [
    { key: 'pk',               label: 'ID',               type: 'id' },
    { key: 'referencia',       label: 'Referência',        type: 'text',   required: true },
    { key: 'titulo',           label: 'Título',            type: 'text',   required: true },
    { key: 'tipo',             label: 'Tipo',              type: 'text',   readonly: true },
    { key: 'carreira',         label: 'Carreira',          type: 'text' },
    { key: 'categoria_prof',   label: 'Categoria Prof.',   type: 'text' },
    { key: 'area_atividade',   label: 'Área Atividade',    type: 'text' },
    { key: 'num_vagas',        label: 'Nº Vagas',          type: 'number' },
    { key: 'municipio',        label: 'Município',         type: 'text' },
    { key: 'estado',           label: 'Estado',            type: 'text',   readonly: true },
    { key: 'data_abertura',    label: 'Data Abertura',     type: 'date' },
    { key: 'data_encerramento',label: 'Data Encerramento', type: 'date' },
    { key: 'visivel',          label: 'Visível',           type: 'boolean' },
    { key: 'descricao',        label: 'Descrição',         type: 'textarea' },
  ],
  listView: { columns: ['referencia', 'titulo', 'carreira', 'estado', 'data_abertura', 'data_encerramento'], defaultSort: { field: 'data_abertura', dir: 'desc' }, searchable: true },
  formView: { sections: [
    { title: 'Procedimento', fields: ['referencia', 'titulo', 'visivel'],                                          cols: 2 },
    { title: 'Detalhe',      fields: ['carreira', 'categoria_prof', 'area_atividade', 'num_vagas', 'municipio'],   cols: 2 },
    { title: 'Datas',        fields: ['data_abertura', 'data_encerramento'],                                        cols: 2 },
    { title: 'Descrição',    fields: ['descricao'],                                                                 cols: 1 },
  ]},
  custom: null,
}
